name: llm_env
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - accelerate=0.31.0
  - aiohttp=3.9.5
  - aiosignal=1.3.1
  - anyio=4.2.0
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - asttokens=2.0.5
  - async-lru=2.0.4
  - async-timeout=4.0.3
  - attrs=23.1.0
  - babel=2.11.0
  - backcall=0.2.0
  - beautifulsoup4=4.12.3
  - bleach=4.1.0
  - brotli-python=1.0.9
  - ca-certificates=2024.3.11
  - certifi=2024.6.2
  - cffi=1.16.0
  - charset-normalizer=3.3.2
  - comm=0.2.1
  - datasets=2.19.2
  - debugpy=1.6.7
  - decorator=5.1.1
  - defusedxml=0.7.1
  - dill=0.3.8
  - exceptiongroup=1.2.0
  - executing=0.8.3
  - filelock=3.14.0
  - frozenlist=1.4.1
  - fsspec=2024.3.1
  - huggingface-hub=0.23.3
  - idna=3.7
  - importlib-metadata=7.0.1
  - importlib_metadata=7.0.1
  - importlib_resources=6.1.1
  - ipykernel=6.28.0
  - ipython=8.12.2
  - jedi=0.18.1
  - jinja2=3.1.4
  - json5=0.9.6
  - jsonschema=4.19.2
  - jsonschema-specifications=2023.7.1
  - jupyter-lsp=2.2.0
  - jupyter_client=8.6.0
  - jupyter_core=5.5.0
  - jupyter_events=0.8.0
  - jupyter_server=2.10.0
  - jupyter_server_terminals=0.4.4
  - jupyterlab=4.0.11
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=2.25.1
  - ld_impl_linux-64=2.38
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libsodium=1.0.18
  - libstdcxx-ng=11.2.0
  - markupsafe=2.1.5
  - matplotlib-inline=0.1.6
  - mistune=2.0.4
  - mpmath=1.3.0
  - multidict=6.0.5
  - multiprocess=0.70.16
  - nbclient=0.8.0
  - nbconvert=7.10.0
  - nbformat=5.9.2
  - ncurses=6.4
  - nest-asyncio=1.6.0
  - networkx=3.1
  - notebook-shim=0.2.3
  - numpy=1.24.4
  - nvidia-cublas-cu12=12.1.3.1
  - nvidia-cuda-cupti-cu12=12.1.105
  - nvidia-cuda-nvrtc-cu12=12.1.105
  - nvidia-cuda-runtime-cu12=12.1.105
  - nvidia-cudnn-cu12=8.9.2.26
  - nvidia-cufft-cu12=11.0.2.54
  - nvidia-curand-cu12=10.3.2.106
  - nvidia-cusolver-cu12=11.4.5.107
  - nvidia-cusparse-cu12=12.1.0.106
  - nvidia-nccl-cu12=2.20.5
  - nvidia-nvjitlink-cu12=12.5.40
  - nvidia-nvtx-cu12=12.1.105
  - openssl=3.0.13
  - overrides=7.4.0
  - packaging=24.1
  - pandas=2.0.3
  - pandocfilters=1.5.0
  - parso=0.8.3
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=10.3.0
  - pip=24.0
  - pkgutil-resolve-name=1.3.10
  - platformdirs=3.10.0
  - prometheus_client=0.14.1
  - prompt-toolkit=3.0.43
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pyarrow=16.1.0
  - pyarrow-hotfix=0.6
  - pycparser=2.21
  - pygments=2.15.1
  - pysocks=1.7.1
  - python=3.8.19
  - python-dateutil=2.9.0post0
  - python-fastjsonschema=2.16.2
  - python-json-logger=2.0.7
  - pytz=2024.1
  - pyyaml=6.0.1
  - pyzmq=25.1.2
  - readline=8.2
  - referencing=0.30.2
  - regex=2024.5.15
  - requests=2.32.3
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rpds-py=0.10.6
  - safetensors=0.4.3
  - send2trash=1.8.2
  - setuptools=69.5.1
  - six=1.16.0
  - sniffio=1.3.0
  - soupsieve=2.5
  - sqlite=3.45.3
  - stack_data=0.2.0
  - sympy=1.12.1
  - terminado=0.17.1
  - tinycss2=1.2.1
  - tk=8.6.14
  - tokenizers=0.19.1
  - tomli=2.0.1
  - torch=2.3.1
  - torchaudio=2.3.1
  - torchvision=0.18.1
  - tornado=6.3.3
  - tqdm=4.66.4
  - traitlets=5.7.1
  - transformers=4.41.2
  - triton=2.3.1
  - typing-extensions=4.12.2
  - typing_extensions=4.11.0
  - tzdata=2024.1
  - urllib3=2.2.1
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - websocket-client=1.8.0
  - wheel=0.43.0
  - xxhash=3.4.1
  - xz=5.4.6
  - yaml=0.2.5
  - yarl=1.9.4
  - zeromq=4.3.5
  - zipp=3.17.0
  - zlib=1.2.13
  - pip:
    - accelerate==0.31.0
    - aiohttp==3.9.5
    - aiosignal==1.3.1
    - anyio==4.2.0
    - argon2-cffi==21.3.0
    - argon2-cffi-bindings==21.2.0
    - asttokens==2.0.5
    - async-lru==2.0.4
    - async-timeout==4.0.3
    - attrs==23.1.0
    - Babel==2.11.0
    - backcall==0.2.0
    - beautifulsoup4==4.12.3
    - bleach==4.1.0
    - Brotli==1.0.9
    - certifi==2024.6.2
    - cffi==1.16.0
    - charset-normalizer==3.3.2
    - comm==0.2.1
    - datasets==2.19.2
    - debugpy==1.6.7
    - decorator==5.1.1
    - defusedxml==0.7.1
    - dill==0.3.8
    - exceptiongroup==1.2.0
    - executing==0.8.3
    - fastjsonschema==2.16.2
    - filelock==3.14.0
    - frozenlist==1.4.1
    - fsspec==2024.3.1
    - huggingface-hub==0.23.3
    - idna==3.7
    - importlib-metadata==7.0.1
    - importlib-resources==6.1.1
    - ipykernel==6.28.0
    - ipython==8.12.2
    - jedi==0.18.1
    - Jinja2==3.1.4
    - json5==0.9.6
    - jsonschema==4.19.2
    - jsonschema-specifications==2023.7.1
    - jupyter_client==8.6.0
    - jupyter_core==5.5.0
    - jupyter-events==0.8.0
    - jupyter-lsp==2.2.0
    - jupyter_server==2.10.0
    - jupyter_server_terminals==0.4.4
    - jupyterlab==4.0.11
    - jupyterlab-pygments==0.1.2
    - jupyterlab_server==2.25.1
    - MarkupSafe==2.1.3
    - matplotlib-inline==0.1.6
    - mistune==2.0.4
    - mpmath==1.3.0
    - multidict==6.0.5
    - multiprocess==0.70.16
    - nbclient==0.8.0
    - nbconvert==7.10.0
    - nbformat==5.9.2
    - nest-asyncio==1.6.0
    - networkx==3.1
    - notebook_shim==0.2.3
    - numpy==1.24.4
    - nvidia-cublas-cu12==12.1.3.1
    - nvidia-cuda-cupti-cu12==12.1.105
    - nvidia-cuda-nvrtc-cu12==12.1.105
    - nvidia-cuda-runtime-cu12==12.1.105
    - nvidia-cudnn-cu12==8.9.2.26
    - nvidia-cufft-cu12==11.0.2.54
    - nvidia-curand-cu12==10.3.2.106
    - nvidia-cusolver-cu12==11.4.5.107
    - nvidia-cusparse-cu12==12.1.0.106
    - nvidia-nccl-cu12==2.20.5
    - nvidia-nvjitlink-cu12==12.5.40
    - nvidia-nvtx-cu12==12.1.105
    - overrides==7.4.0
    - packaging==23.2
    - pandas==2.0.3
    - pandocfilters==1.5.0
    - parso==0.8.3
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - pillow==10.3.0
    - pip==24.0
    - pkgutil_resolve_name==1.3.10
    - platformdirs==3.10.0
    - prometheus-client==0.14.1
    - prompt-toolkit==3.0.43
    - psutil==5.9.0
    - ptyprocess==0.7.0
    - pure-eval==0.2.2
    - pyarrow==16.1.0
    - pyarrow-hotfix==0.6
    - pycparser==2.21
    - Pygments==2.15.1
    - PySocks==1.7.1
    - python-dateutil==2.9.0.post0
    - python-json-logger==2.0.7
    - pytz==2024.1
    - PyYAML==6.0.1
    - pyzmq==25.1.2
    - referencing==0.30.2
    - regex==2024.5.15
    - requests==2.32.2
    - rfc3339-validator==0.1.4
    - rfc3986-validator==0.1.1
    - rpds-py==0.10.6
    - safetensors==0.4.3
    - Send2Trash==1.8.2
    - setuptools==69.5.1
    - six==1.16.0
    - sniffio==1.3.0
    - soupsieve==2.5
    - stack-data==0.2.0
    - sympy==1.12.1
    - terminado==0.17.1
    - tinycss2==1.2.1
    - tokenizers==0.19.1
    - tomli==2.0.1
    - torch==2.3.1
    - torchaudio==2.3.1
    - torchvision==0.18.1
    - tornado==6.3.3
    - tqdm==4.66.4
    - traitlets==5.7.1
    - transformers==4.41.2
    - triton==2.3.1
    - typing_extensions==4.11.0
    - tzdata==2024.1
    - urllib3==2.2.1
    - wcwidth==0.2.5
    - webencodings==0.5.1
    - websocket-client==1.8.0
    - wheel==0.43.0
    - xxhash==3.4.1
    - yarl==1.9.4
    - zipp==3.17.0
